export default {
  'menu.sys': "系统管理",
  'menu.co': "公司管理",
  'menu.cus': "客户管理",
  'menu.svr': "接口服务管理",
  'menu.dev': "硬件管理",
  'menu.log': "日志管理",
  'menu.dev.device': "设备管理",
  'menu.dev.deviceType': "产品类型管理",
  'menu.dev.model': "模组管理",
  'menu.svr.emqxServer': "MQTT服务器管理",
  'menu.svr.apiServerList': "API服务器管理",
  'menu.log.apiLog': "API日志管理",
  'menu.log.deviceLog': "设备日志管理",
  'menu.co.staff': "员工管理",
  'menu.co.role': "角色管理",
  'menu.cus.thirdPartySystem': "第三方系统管理",
  'menu.sys.sysConfig': "系统配置管理",
  'menu.sys.permission': "权限点管理",
  'menu.sys.dictionary': "字典管理",
};